version: '2.4'
services:
  smpp21:
    image: "winnovature/unitia:29may2021_1"
    mem_limit: 2g
    ports:
      - "2777:8080"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=smpp2
      - port=2777
      - TZ=Asia/Kolkata
  smpp22:
    image: "winnovature/unitia:29may2021_1"
    mem_limit: 2g
    ports:
      - "2778:8080"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=smpp2
      - port=2778
      - TZ=Asia/Kolkata
