version: '3'
services:
  qdb1:
    image: "winnovature/mariadb:production"
    ports:
      -  "9001:3306"
    volumes:
      - "/home/unitia/production/qdb1:/var/lib/mysql"
      - "/home/unitia/production/qdb1/my.cnf:/etc/mysql/my.cnf"
    environment:
      - MYSQL_ROOT_PASSWORD=kannel 
      - TZ=Asia/Kolkata
  qdb2:
    image: "winnovature/mariadb:production"
    ports:
      -  "9002:3306"
    volumes:
      - "/home/unitia/production/qdb2:/var/lib/mysql"
      - "/home/unitia/production/qdb2/my.cnf:/etc/mysql/my.cnf"
    environment:
      - MYSQL_ROOT_PASSWORD=kannel
      - TZ=Asia/Kolkata
  qdb3:
    image: "winnovature/mariadb:production"
    ports:
      -  "9003:3306"
    volumes:
      - "/home/unitia/production/qdb3:/var/lib/mysql"
      - "/home/unitia/production/qdb3/my.cnf:/etc/mysql/my.cnf"
    environment:
      - MYSQL_ROOT_PASSWORD=kannel
      - TZ=Asia/Kolkata

