version: '2.4'
services:
  scheduledb:
    image: "winnovature/unitia:23apr2021_1"
    mem_limit: 2g
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=scheduledb
      - TZ=Asia/Kolkata
