version: '3'
services:
  unitiadb:
    image: "winnovature/mariadb:production"
    ports:
      -  "3306:3306"
    volumes:
      - "/home/unitia/production/mysql:/var/lib/mysql"
      - "/home/unitia/production/mysql/my.cnf:/etc/mysql/my.cnf"
    environment:
      - MYSQL_ROOT_PASSWORD=kannel 
      - TZ=Asia/Kolkata
