version: '2.4'
services:
  router1:
    image: "winnovature/unitia:29may2021_1"
    mem_limit: 2g
    volumes:
      - /logs:/logs
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    environment:
      - module=router
      - redis=rq2
      - priority=1
      - TZ=Asia/Kolkata
