version: '2.4'
services:
  dnhttppostinsert:
    image: "winnovature/unitia:29may2021_1"
    mem_limit: 2g
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=dnhttppostinsert
      - redis=rq2      
      - TZ=Asia/Kolkata
  dnhttppostinsert1:
    image: "winnovature/unitia:29may2021_1"
    mem_limit: 2g
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=dnhttppostinsert
      - redis=rq3
      - TZ=Asia/Kolkata
  dnhttppostselect:
    image: "winnovature/unitia:29may2021_1"
    mem_limit: 2g
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=dnhttppostselect
      - TZ=Asia/Kolkata

