version: '3'
services:
  dnhttppostinsert:
    image: "winnovature/unitia:31mar2021_1"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=dnhttppostinsert
      - redis=rq2      
      - TZ=Asia/Kolkata
  dnhttppostselect:
    image: "winnovature/unitia:31mar2021_1"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=dnhttppostselect
      - TZ=Asia/Kolkata

