version: '2.4'
services:
  simulator1:
    image: "winnovature/unitia:23apr2021_1"
    mem_limit: 2g
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=simulator
      - TZ=Asia/Kolkata
  kannel1:
    image: "product2/kannel:sqldn"
    ports:
      - "13013:13013" # smsbox
      - "13000:13000" # kannel admin
    depends_on:
      - kannelconfig
    volumes:
      - "/home/unitia/production/spool/kannelA:/var/spool/kannel"
      - "/logs/kannelA:/var/log/kannel"
      - "/etc/hosts:/etc/hosts"
      - "/home/unitia/production/kannelA:/etc/kannel"
      - "./opensmppbox.conf:/etc/kannel/opensmppbox.conf"
    environment:
      - "LANG=en_US.UTF-8"
      - "LC_ALL=en_US.UTF-8"
  kannelconfig:
    image: "winnovature/unitia:23apr2021_1"
    mem_limit: 2g
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=kannelconfig
      - TZ=Asia/Kolkata
