version: '3'
services:
  queuecheck:
    image: "winnovature/unitia:24jan2021"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=queuecheck
      - TZ=Asia/Kolkata

