version: '2.4'
services:
  optin:
    image: "winnovature/unitia:29may2021_1"
    mem_limit: 2g
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=optin
      - TZ=Asia/Kolkata
  optout:
    image: "winnovature/unitia:29may2021_1"
    mem_limit: 2g    
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=optout
      - TZ=Asia/Kolkata
  duplicate:
    image: "winnovature/unitia:29may2021_1"
    mem_limit: 2g
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=duplicate
      - TZ=Asia/Kolkata
