version: '2.4'
services:
  dnreceiver1:
    image: "winnovature/unitia:29may2021_1"
    mem_limit: 2g
    ports:
      - "6001:8080"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=dnreceiver
      - TZ=Asia/Kolkata
  dnreceiver2:
    image: "winnovature/unitia:29may2021_1"
    mem_limit: 2g
    ports:
      - "6002:8080"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=dnreceiver
      - TZ=Asia/Kolkata
  dn:
    image: "dn-haproxy:latest"
    mem_limit: 2g
    ports:
      - "8777:8080"
    depends_on:
      - "dnreceiver1"
      - "dnreceiver2"
