version: '3'
services:
  dnsql:
    image: "winnovature/unitia:23apr2021_1"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=dnsql
      - kannelid=kannel2
      - TZ=Asia/Kolkata

