version: '3'
services:
  admin:
    image: "winnovature/unitia:24jan2021" 
    ports:
      - "8009:8080"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs 
    environment:
      - module=admin
      - TZ=Asia/Kolkata  
