version: '3'
services:
  http1:
    image: "winnovature/unitia:20jan2021" 
    ports:
      - "8001:8080"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs 
    environment:
      - module=http
      - TZ=Asia/Kolkata  
  http2:
    image: "winnovature/unitia:20jan2021"
    ports:
      - "8002:8080"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=http
      - TZ=Asia/Kolkata
  smpp:
    image: "winnovature/unitia:20jan2021"
    ports:
      - "2775:8080"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=smpp
      - TZ=Asia/Kolkata
  http:
    image: "http-haproxy:latest"
    ports:
      - "9090:8080"
    depends_on:
      - "http1"
      - "http2"
