cp -rp http* /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp smpp1 /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp smpp2 /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp creditupdate /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp dn /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp kannelconnector2 /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp cdacconnector /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp router /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp queuecheck /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp aux /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp concate /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp dnhttppost /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp dnquerylog /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp requestlog /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp submission /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp delivery /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp dbtoredis /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp tablereader /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp dnpostdb /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp scheduledb /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp pushbackup.sh /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp restart.sh /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp stop.sh /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp dnsql /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp kanneldb /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp queuedb /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp reroutekannel /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp concate /home/jaffer/unitiabuild/unitia-01-64/.
