cp -rp http* /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp smpp /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp billing /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp creditupdate /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp dn /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp kannelconnector /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp cdacconnector /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp router /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp queuecheck /home/jaffer/unitiabuild/unitia-01-64/.
cp -rp aux /home/jaffer/unitiabuild/unitia-01-64/.
