version: '2.4'
services:
  cdacconnector:
    image: "winnovature/unitia:31mar2021_1"
    mem_limit: 2g
    volumes:
      - /logs:/logs
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    environment:
      - module=cdacconnector
      - redis=rq2
      - TZ=Asia/Kolkata
      - kannelid=cdac
